#背景相关
#设置背景不透明度

background_image /home/liuzhuoqi/Downloads/macos-catalina-mountains-island-evening-twilight-sunset-3840x2160-4009.jpg
background_image_opacity 0.1
background_image_layout scaled
background_tint 0.7

background_image_darken 0.3
foreground #cdd6f4
dynamic_background_opacity yes
# 使用乘法混合模式增强文字可读性
background_image_composite "multiply"

# 边框圆角半径
window_border_radius 8

#光标
cursor_trail 3
#启用光标行高亮
cursorline yes
#光标颜色
cursorline_color #3a3a3a

#光标文本颜色
cursorline_text_color #ffffff

#光标样式增强
cursor_shape beam
cursor_thinckness 2.0
cursor_blink yes

#隐藏窗口装饰
hide_window_decorations no

linux_display_server x11
