require("render-markdown").setup({
  heading = {
    sign = false,
    position = "inline",
    width = "block",
    left_margin = 0.5,
    left_pad = 0.2,
    right_pad = 0.2,
  },
  sign = {
    enabled = true,
    priority = nil,
    highlight = "RenderMarkdownSign",
  },
  paragraph = {
    enabled = true,
    render_modes = false,
    left_margin = 0,
    indent = 0,
    min_width = 0,
  },
  bullet = { icons = { { "󰫶 ", "󱂉 " } } },
  link = {
    enabled = true,
    render_modes = false,
    footnote = {
      enabled = true,
      icon = "󰯔 ",
      body = function(ctx)
        return ctx.text
      end,
      superscript = true,
      prefix = "",
      suffix = "",
    },
    image = "󰥶 ",
    image_custom = true,
    email = "󰀓 ",
    hyperlink = "󰌹 ",
    highlight = "RenderMarkdownLink",
    highlight_title = "RenderMarkdownLinkTitle",
    wiki = {
      enabled = true,
      icon = "󱗖 ",
      body = function()
        return nil
      end,
      highlight = "RenderMarkdownWikiLink",
      scope_highlight = nil,
    },
    custom = {
      web = { pattern = "^http", icon = "󰖟 " },
      apple = { pattern = "apple%.com", icon = " " },
      discord = { pattern = "discord%.com", icon = "󰙯 " },
      github = { pattern = "github%.com", icon = "󰊤 " },
      gitlab = { pattern = "gitlab%.com", icon = "󰮠 " },
      google = { pattern = "google%.com", icon = "󰊭 " },
      hackernews = { pattern = "ycombinator%.com", icon = " " },
      linkedin = { pattern = "linkedin%.com", icon = "󰌻 " },
      microsoft = { pattern = "microsoft%.com", icon = " " },
      neovim = { pattern = "neovim%.io", icon = " " },
      reddit = { pattern = "reddit%.com", icon = "󰑍 " },
      slack = { pattern = "slack%.com", icon = "󰒱 " },
      stackoverflow = { pattern = "stackoverflow%.com", icon = "󰓌 " },
      steam = { pattern = "steampowered%.com", icon = " " },
      twitter = { pattern = "twitter%.com", icon = " " },
      wikipedia = { pattern = "wikipedia%.org", icon = "󰖬 " },
      x = { pattern = "x%.com", icon = " " },
      youtube = { pattern = "youtube[^.]*%.com", icon = "󰗃 " },
      youtube_short = { pattern = "youtu%.be", icon = "󰗃 " },
    },
  },
  heading = { border = true },
  indent = { enabled = true },
})
